### ISSUE TITLE
Sort by on device lists page does not match mockups

### ISSUE THREAD

**Issue by gdzooks** [bean-pod/switchboard#107]
**Operating system:** 
 

* Windows 10
* Google Chrome

**Steps to reproduce:**
 
1. Run the frontend (npm start)
2. Select an option from the Sort By select.

**Expected result:**

* Width of the Sort by should be fixed.
* Width of the Sort by should be the width of its longest option.

**Actual result:**
 
* Width of the Sort by changes depending on the selected option.
* Width of the Sort by is shorter than the longest option that can be selected.

**Visual proof:**
 
|  Actual  |
|:---------------:|
| ![image](https://user-images.githubusercontent.com/22307286/97251604-94b4fd80-17de-11eb-9069-91976d73d388.png) |
| ![image](https://user-images.githubusercontent.com/22307286/97251662-ae564500-17de-11eb-98c5-54b9f2c52435.png) |
| ![image](https://user-images.githubusercontent.com/22307286/97251699-ba420700-17de-11eb-8d5a-d9389cce3165.png) |

| Expected |
|:---------------:|
| ![image](https://user-images.githubusercontent.com/22307286/97251771-e65d8800-17de-11eb-8870-33215ffe2e87.png) |

**Comment by sharon-ho** [comment]
Since the implementation of the `material-table` data table library in the project, we no longer require a separate sort by dropdown.
