### ISSUE TITLE
Investigate UDP hole punching

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#11]
PM recommended using UDP hole punching to accomplish the creation of a stream between sender and receiver. Investigate this method to determine
- How it works
- What are the pros and cons
- Do there exist alternative methods
- What would we have to do in the server code to accomplish this

The output of this task is a document that addresses the above questions

Once this task is complete, we should have all the knowledge necessary to do the tasks in [the epic user story for sending video from the sender to receiver](https://app.zenhub.com/workspaces/capstone-5f590eb91f576c0012610a55/issues/felixlapierre/switchboard/20).

**Comment by ButlerJAL** [comment]
Please consult, review, and comment on the [Investigate UDP hole punching documentation](https://docs.google.com/document/d/1dqI9cYBFItKGcH8kaqlNtDGPAS_Fv6C3sZi2jKHaSck/edit?usp=sharing) found in our Google Drive. Do not hesitate to ask me for more details on certain areas of my investigation, so, I could update the documentation in the case that there remains uncertainty.

**Comment by ButlerJAL** [comment]
Done.
