### ISSUE TITLE
Warning: Invalid DOM property `class`. Did you mean `className`?

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#113]
Steps to reproduce:
- Run the frontend project with `npm run start`
- Open the page in your web browser, such as Chrome, at `localhost:3000`
- Open the inspector and view the console output

Desired output:
- No warnings or errors

Actual output:
- Warning: Invalid DOM property `class`. Did you mean `className`?

**Comment by ButlerJAL** [comment]
@felixlapierre can this bug be closed? I believe this is no longer applicable.

**Comment by gdzooks** [comment]
> @felixlapierre can this bug be closed? I believe this is no longer applicable.

i think we've fixed all occurences of this one way or another through various PRs & we haven't had the error since so i'm down with closing !
