### ISSUE TITLE
Back-end can't connect to database if the database hasn't manually been logged in before

### ISSUE THREAD

**Issue by FGRCL** [bean-pod/switchboard#117]
**Operating system:** 
Should happen on all OS, confirmed on Linux and Windows

**Steps to reproduce:**

1. Start a mysql database
2. Start the backend application
3. The application fails to start because it can't connect to the database

**Expected result:**
- Back-end properly starts

**Actual result:**
- Application crashes at boot

**Comment by felixlapierre** [comment]
Not an issue anymore since we have a development profile which allows the DB connections when user hasn't logged into the db before
