### ISSUE TITLE
Acceptance Test for #52 As a user, I want to register a decoder in the system

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#128]
Prerequisites
- Database server, backend, and frontend are running

Steps
- Start the sample decoder user interface
- Enter a device name and serial number
- Click "register"
- Open the admin panel
- Click on the "receivers" tab

Expected result
- The decoder that was just registered is present in the device list

**Comment by dmalon** [comment]
This story passed the acceptance test.

Good Job Team!

**Comment by felixlapierre** [comment]
Thanks Dan!!
