### ISSUE TITLE
Acceptance Test for #18 As a user, I want to register an encoder in the system

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#130]
Prerequisites
- Database server, backend, and frontend are running

Steps
- Start the sample encoder user interface
- Enter a device name and serial number
- Click "register"
- Open the admin panel

Expected result
- The encoder that was just registered is present in the device list

**Comment by dmalon** [comment]
This story passed the acceptance test

**Comment by felixlapierre** [comment]
Thanks Dan!!
