### ISSUE TITLE
Acceptance Test for #19 As a user, I want to view devices in the system

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#131]
Prerequisites
- Database server, backend, and frontend are running
- There is at least one encoder and one decoder registered in the system

Steps
- Open the frontend

Expected
- All encoders that are registered in the system are displayed on the page with their name, serial number, IP address, and status indicated.

Steps
- Click on the "receivers" tab

Expected
- All decoders that are registered in the system are displayed on the page, with their name, serial number, IP address, and status indicated.

**Comment by dmalon** [comment]
This story passed the acceptance test

**Comment by felixlapierre** [comment]
Thanks Dan!!
