### ISSUE TITLE
Acceptance Test for #20 As a user, I want to initiate a stream between a sender and a receiver

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#132]
Prerequisites
- Database, backend and frontend are running

Steps
- Start the sample encoder
- Enter a device name and serial number
- Click on the "register" button
- In the "streaming instructions" section, click on "Browse" and select an mp4 file to be streamed
- Start the sample decoder
- Enter a device name and serial number
- Click on the "register" button
- Open the frontend admin panel
- Click on the "stream" button
- From the list of senders, click on the encoder that you have opened
- From the list of receivers, click on the decoder that you have opened
- Click on the "stream" button

Expected result
- A new window should open on the system with the sample decoder within 10 seconds
- The window should display the mp4 file that was selected on the sample encoder

**Comment by dmalon** [comment]
This story passed the acceptance test

**Comment by felixlapierre** [comment]
Thanks Dan!!
