### ISSUE TITLE
App should run when component pieces are on different systems

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#146]
Right now, a lot of our code is hardcoded to specific URLs or to localhost. For example, the URL of the server is hardcoded to Localhost in the sample apps and in the frontend. We should fix this so the url is dynamic / configurable.
- For frontend: see what the standard is for specifying the URL of the backend in a react app
- For sample apps: use a configuration file where we can set the URL of the server

**Comment by ButlerJAL** [comment]
@felixlapierre, fyi, this issue has been addressed in PR #209 with the introduction of environment variables for the frontend and Spring Profiles in the backend.

**Comment by ButlerJAL** [comment]
@arejayelle, I noted you started working on a similar solution to solve the frontend portion of this issue in particular on one of your development branches:

&ensp; _146-specify-deploy-url-frontend_

Have a review of #209 before continuing where you left off on that branch, Thanks!
