### ISSUE TITLE
Decoders/Encoders can be created with no video channels

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#155]
Steps to reproduce:
- Create a device with a `POST localhost:8080/device`
- Create a decoder with `POST localhost:8080/decoder` with the following body
```
{
    "serialNumber": "{serial number}",
    "inputs": []
}
```
Expected: Error, a decoder/encoder must have at least one video channel
Actual: No error, it lets you create the decoder

**Comment by mohhef** [comment]
Not sure if understand the expected behavior here. You are not allowed to create a decoder with empty inputs?
