### ISSUE TITLE
Create mockups for Release 1 features

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#16]
Create mockups for Frontend stories that will be included in Release 1.

- [x] - [See list of devices in the system](https://app.zenhub.com/workspaces/capstone-5f590eb91f576c0012610a55/issues/felixlapierre/switchboard/24)
- [x] - [See detailed information about a device](https://app.zenhub.com/workspaces/capstone-5f590eb91f576c0012610a55/issues/felixlapierre/switchboard/25)
- [x] - [Edit information about a device](https://app.zenhub.com/workspaces/capstone-5f590eb91f576c0012610a55/issues/felixlapierre/switchboard/26)
- [x] - [Delete a device](https://app.zenhub.com/workspaces/capstone-5f590eb91f576c0012610a55/issues/felixlapierre/switchboard/27)
- [x] - [Initiate a stream between a sender and a receiver](https://app.zenhub.com/workspaces/capstone-5f590eb91f576c0012610a55/issues/felixlapierre/switchboard/28)

**Comment by felixlapierre** [comment]
Sharon take lead on this

**Comment by sharon-ho** [comment]
Mockups found here: https://www.figma.com/file/mtnbVrHXduQsiYjTkbLTbi/Switchboard?node-id=0%3A1
