### ISSUE TITLE
Styling issues in Device List page

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#185]
**Steps to reproduce:**
- Run the frontend
- Open the device list page

**Expected result:**
![image.png](https://images.zenhubusercontent.com/5e15d6546da42b6dfe054be4/b44c572c-67b3-4090-91a1-472fb57067ae)

**Actual result:**
![image.png](https://images.zenhubusercontent.com/5e15d6546da42b6dfe054be4/0096396a-fd8d-4bc4-8c7f-8fef13002732)

Left-side column is less wide than it used to be. Senders and Receivers text is horizontally aligned to match the old width, so they are too close to the right.

Rows in the device list table have too much vertical width, and there are large grey bars between entries.

These issues arose when fixing code smells in #148

**Comment by sharon-ho** [comment]
Closing this issue because the styling for the Device List page is no longer as shown in this bug report ever since the `material-table` data table library has been implemented into the project.
