### ISSUE TITLE
ConvertDataFormat not used in DeviceApi

### ISSUE THREAD

**Issue by jun-loke** [bean-pod/switchboard#204]
### Operating system:
All

#### Description

As of right now, `DeviceInfo.convertToDataObject` only reads the `inputs ` property of the service object being passed. 

This SHOULD cause all service objects being passed to only be created with channels if they have an `inputs` property because DataObjects in the frontend only have a `channels` property, since the difference between inputs and outputs isn't important.

This is not breaking anything because we aren't using our Adapter, but we SHOULD be using it.

 

#### Steps to reproduce:
 
- Look at the code
- Look how ConverDataFormat is not used in DeviceApi
- Feel sad
##### Expected result:
 
- Being used
##### Actual result:
 
- sadness
##### Visual Proof:
N/A

**Comment by gdzooks** [comment]
`convertToDataObject` is being used in StreamApi now, should we close this bug?
i don't think we need `convertToServiceObject` since every time we make a model we just grab the info we want and plop it into the right places in the model constructors

**Comment by felixlapierre** [comment]
Closed because this bug does not apply anymore
