### ISSUE TITLE
Endpoint to get all logs associated with a device

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#217]
When viewing a device's details, we want to be able to see all the logs related to a device. For this we need a GET endpoint that takes the serial number of a device and returns a list of logs related to that device.

Right now, the id of the device that generated the log is in the message string, which is not easy to query. We want to easily be able to query which device made the log. Note that we also need a log to be generated by two devices (such as when logging the creation of a stream).

**Comment by mohhef** [comment]
Would it not be better to just simply use material tables on the FE and just type in the search box ''ID 15'' or ''Serial Number 15''
which conforms to that device that way all the rows will be shown without the need for a separate controller. That is why i did not add that controller to my previous pr, however i did not explictly mention it
