### ISSUE TITLE
Acceptance test for #49 As a user, I want to end a stream between a sender and a receiver

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#223]
Acceptance test for #49 As a user, I want to end a stream between a sender and a receiver

Steps
1. Run the backend and frontend
2. Open the streaming page
3. Open two sample apps and register them in the system
4. Create a stream between the two sample apps
5. Refresh the page
6. The stream should be visible in the streaming page
7. Click on the delete button on the right of the entry in the streaming table
8. Refresh the page
9. The stream should no longer be visible

**Comment by dmalon** [comment]
As PM I consider this story complete and closed
