### ISSUE TITLE
Acceptance test for #136 As a user, I want to view a list of streams in the system

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#224]
Acceptance test for #136 As a user, I want to view a list of streams in the system

Steps:
1. Run the backend and frontend and two sample apps
2. Register the sample apps
3. Open the admin panel
4. Open the streaming page
5. Select the sample sender and the sample receiver
6. Click "stream" to create the stream
7. Refresh the page
8. The stream should be visible on the page.
9. Register another pair of sample apps
10. Create a stream between the new pair of sample apps
11. Refresh the page
12. Both streams should now be visible in the list

**Comment by dmalon** [comment]
As PM as consider this story complete and closed
