### ISSUE TITLE
Acceptance test for #46 As a user, I want to see which of my devices are active and which ones are inactive

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#225]
Acceptance test for #46 As a user, I want to see which of my devices are active and which ones are inactive

Steps:
1. Run the backend, frontend, and the sample sender or receiver.
2. Click the register button on the sample app
3. Open the Devices page
4. The registered device should appear in the list with a status of "Pending"
5. Click "start" on the sample app to start polling the server
6. Refresh the device list page
7. The registered device should now have a status of "Online"
8. Close the sample apps
9. Wait ten minutes
10. Refresh the device list page
11. The registered device should now have a status of "Offline"

**Comment by dmalon** [comment]
As PM I consider this story complete and closed
