### ISSUE TITLE
Acceptance test for #55 As a user, I want to initiate a stream between two devices that are on different networks without manually doing NAT traversal

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#226]
Acceptance test for #55 As a user, I want to initiate a stream between two devices that are on different networks without manually doing NAT traversal

Steps:
1. Run the backend and frontend
2. Open the sample sender and the sample receiver on two different systems, that are on two different networks (i.e. two different home networks)
3. Register both sample apps
4. Select a video source on the sample sender, either a mp4 file or the webcam
5. Click start on both sample apps
6. Click register on both sample apps
7. Open the admin panel
8. Open the streaming page
9. Create a stream between the two devices
10, On the sample receiver, the video stream should appear.

**Comment by dmalon** [comment]
As PM, I consider this story complete and closed
