### ISSUE TITLE
Acceptance test for #53 As a user, I want to delete devices in the system

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#227]
Acceptance test for #53 As a user, I want to edit and delete devices in the system

Steps
1. Run the frontend, backend, and a sample app
2. Click register on the sample app
3. Open the admin panel
4. Open the device list page
5. Click on the device in the list to go to the device details page
10. Click on the delete button
11. You should be returned to the device list page
12. The device should no longer be present in the list.

**Comment by dmalon** [comment]
As Product Owner I consider this story complete
