### ISSUE TITLE
Performance Testing

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#229]
Record service logs using logging libraries, and perform Load and Stress testing. Analyze the collected data to find ways to improve the server performance

- Add logs in the service that track performance
- Set up Jmeter locally to test against deployed service on Heroku
- Record results for a load of 100 users with 10 devices each
- Analyze the results and highlight improvement opportunities

**Comment by mohhef** [comment]
@felixlapierre I had 2 questions
1- Is adding logs within the scope of this issue?
2- There are a lot of endpoints, I don't think we should test all endpoints only the ones highly utilized.
I think these will be mostly the GET endpoints, do you have specific requirements on which endpoints to test?

**Comment by felixlapierre** [comment]
> 
> 
> @felixlapierre I had 2 questions?
> 1- Is adding logs within the scope of this issue?
> 2- There are a lot of endpoints, I don't think we should test all endpoints only the ones highly utilized.
> I think these will be mostly the GET endpoints, do you have specific requirements on which endpoints to test?

1 - Yes. The prof's instructions say "Record service logs using logging libraries" but doesn't give more detail for that, so i'll leave the details for which logs to create up to you.
2 - I agree with you, but during the TA meeting, the TA said we had to test all endpoints, but we only have to focus on the important endpoints when looking for improvements. So make sure they're tested but don't put as much focus on them.
