### ISSUE TITLE
"production" profile's data source fails on local machine 

### ISSUE THREAD

**Issue by jun-loke** [bean-pod/switchboard#249]
"production" profile's Datasource fails on local machine.

The environment variable `CLEARDB_DATABASE_URL` is not being set automatically.

**Comment by felixlapierre** [comment]
The real issue here is that IntelliJ community edition uses the production profile and I haven't been able to get it to change the profile it's using by passing command line arguments. If anyone was able to get this to work in community edition please advise me.
