### ISSUE TITLE
Detailed device information page

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#25]
When clicking on a device in the list, the user should see detailed information. This should contain every bit of information that is relevant to the user (basically everything other than the internal database ID).

### Mockup
![0002.jpg](https://images.zenhubusercontent.com/5e1cf02ce040605817d94ec2/34b0548a-531a-4f26-9f36-e93362a24d54)

### Annotated
![Device Details.jpg](https://images.zenhubusercontent.com/5e1cf02ce040605817d94ec2/acef3f3d-98ed-4f97-86d4-22a00bfbd034)

**Comment by jun-loke** [comment]
Use https://dev.to/dsckiitdev/dynamic-pages-using-react-router-2pm to figure out routing
