### ISSUE TITLE
Endpoint for receivers to send SRT stream statistics to the server

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#267]
Once #269 is completed and we know what statistics we want to track for SRT, we should create an endpoint for devices to provide statistics about a stream. 

Possible designs:

* Have the statistics as a property of the stream object, and simply call PUT /streams/{id}
* Have the statistics in their own table and POST/PUT a statistics object, and have a one-to-one relation between streams and statistics
* Have the statistics as a property of the stream, but they must be created/updated using a POST/PUT /streams/{id}/statistics

Also, what do we do when there are no statistics provided yet? Devices shouldn't have to do POST the first time they push statistics and PUT after that; they should just send their statistics and let the server record them.

We should also create a GET endpoint for these statistics to be retrieved in the frontend to be displayed.

**Comment by mohhef** [comment]
@felixlapierre  I remember you wanted to add something to the description of this task last meeting, is  it good now?

I am not sure what do you mean by:
"Also, what do we do when there are no statistics provided yet? Devices shouldn't have to do POST the first time they push statistics and PUT after that; they should just send their statistics and let the server record them"

is it possible to elaborate on when we would want to persist statistics to the database (i.e. is it when a stream ends?, are we persisting statistics multiple times while a stream is happening?)

Is there specific attributes you have in mind for the statistics object, i see there are a lot of attributes in #269  investigation

**Comment by felixlapierre** [comment]
The description is good now!

The way this is going to work is that the receiver will send a request to the server every 10 seconds or something where it will provide the stream statistics. Like this, the user can view how the stream is going any time in our admin panel. 

When the stream is created, there will be no recorded statistics yet. It's only once the stream starts that the device will start sending them. So in the beginning of the life of the stream, there will be no statistics recorded yet. Then we will receive the statistics from the device for the first time, and we will have statistics values stored. After another 10 seconds, the device will send statistics once more, and the statistics we have in the database will be overwritten by the new values.

The way we do it for things like devices, we usually do a POST request to create the device, then later if we want to update that data we do a PUT request. I don't want to do this mechanism for statistics, because then the device will have to do a POST request when pushing the statistics for the first time, and do a PUT request whenever they want to overwrite with new values. If we do that, the device will need to check / remember if this is the first time they sent statistics for the stream, which complicates the logic on the sample app side. I would prefer if there were a single endpoint which the device sends its statistics to, and the server will create a new statistics object if statistics have never been sent yet, and update the existing one if statistics have already been sent.

Once we delete the stream, we will delete the statistics too.

As for which specific attributes we have in mind, I was thinking of recording all of the attributes in #269, but I'll ask the PM if that is what they want or not.

Let me know if this answers your questions!

**Comment by mohhef** [comment]
@felixlapierre  Thank you for the clarification, just a few more questions.
"It's only once the stream starts that the device will start sending them", here device means receiver?
"If we do that, the device will need to check / remember if this is the first time they sent statistics for the stream", here device means receiver, correct?

is this statement from my understanding accurate -> for each stream it should have a statistic (e.g. stream 1, should have a unique statistics attached to that unique stream) in which this statistic is updated by the **receiver** of the stream

**Comment by felixlapierre** [comment]
Yes that is correct! Only the receiver is sending statistics at the moment, and streams have unique statistics attached
