### ISSUE TITLE
Log-in page

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#273]
Create a log in page, that takes a username and password (or whatever our choice of authentication method requires), has a login button.

* If login is successful, persist the session and redirect to the homepage
* If login fails, display an error and redirect to / remain on the log in page.

Calls the endpoint created in #272

For convenience, we should make sure that you don't need to log back in to the frontend constantly. The session should persist if you restart the frontend.

**Comment by jun-loke** [comment]
Wireframe
Achtung! Only use this for placement of information and not for actual colour scheme.
![image](https://user-images.githubusercontent.com/35614138/106817928-8e3bea80-6645-11eb-9c7a-376e6411318a.png)
