### ISSUE TITLE
Stream creation page

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#28]
The user should be able to select a sender and a receiver, and indicate "start stream" or something similar. This will then make the appropriate call to the server to start the stream.

### Mockup
![0007.jpg](https://images.zenhubusercontent.com/5e1cf02ce040605817d94ec2/4b12b54b-698e-494e-a062-069c33dba30f)

### Annotated
![Streaming.jpg](https://images.zenhubusercontent.com/5e1cf02ce040605817d94ec2/411998ee-ecc3-4050-92d7-c77603056fe6)

**Comment by jun-loke** [comment]
This fixes #109
