### ISSUE TITLE
Acceptance criteria for #33 As a user, I want to restrict access to devices that I own

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#284]
Steps:
- Start the frontend and backend
- Register the sample sender and sample receiver as the superuser account (username: admin, password: admin in development environment)
- Open the frontend
- Go to the stream creation page
- Create a stream between the sample sender and sample receiver
- Create a new account (either using the create account page in the frontend, or using postman to directly send the request)
- Log out of the frontend by clicking the user icon on the right of the header bar
- Log in to the frontend with the newly created account
- Navigate to the device list page
- No devices should be visible / the devices belonging to the super user should not be visible
- Navigate to the stream list page
- The previously created stream should not be visible
- Navigate to the logs page
- No logs should be visible / The logs related to the previous user's activity should not be visible

**Comment by dmalon** [comment]
As the PO I consider this story complete and closed.

**Comment by felixlapierre** [comment]
Thanks Dan!
