### ISSUE TITLE
Acceptance criteria for #44 As a user, I want to initiate streams from multiple senders to multiple receivers

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#285]
Steps:
- Start the frontend and backend
- Register the sample sender and sample receiver
- On the sample sender, select two different video files to send
- Click start on the sample sender and sample receiver
- Open the frontend
- Go to the stream creation page
- Create a stream between the first channels of each device
- Create a stream between the second channels of each device

Expected result:
- Two windows open, with each video streaming one of the selected video files

**Comment by dmalon** [comment]
As PO I consider this story complete and closed

**Comment by felixlapierre** [comment]
Thanks Dan!
