### ISSUE TITLE
Acceptance test for #48 As a user, when an event occurs during a stream, I want to see an event message in the admin panel

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#287]
Steps:
- Start the frontend and backend
- Start the sample sender and sample receiver
- Register the sample sender and sample receiver in the system
- Open the frontend
- Navigate to the stream creation page
- Create a stream between your sample sender and sample receiver
- Close the sample sender before the stream is concluded
- Go to the stream details page
- In the stream logs component, a log should appear with events that happened during the stream

**Comment by dmalon** [comment]
As a PO, i consider this story complete and closed. As an optimization, the web page could be designed to auto refresh if a message is posted while the user is viewing the logs.

**Comment by felixlapierre** [comment]
Thanks Dan, and thank you for the feedback!
