### ISSUE TITLE
Acceptance test for #50 As a user, I want to provide custom configuration to my sender devices

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#288]
Steps:
- Start the frontend and backend
- Start the sample sender and sample receiver
- Select the webcam on the sample sender
- Click start on both sample apps
- Start a stream between the two devices, from channel 1 of the sender to channer 1 of the receiver
- A stream should appear at our default resolution of 1280x720 and the default FPS of 7.5
- Delete the stream
- Close the sample sender and receiver
- Open the device details page of the sender
- Click on "Upload" in the configuration section
- Upload a file with the following contents
```
{
    "camera": {
        "video_size": "800x600",
        "framerate": "30"
    }
}
```
- Open the sample sender and select the webcam streaming. Open the sample receiver.
- Click start on both devices
- Open the create stream page and create a stream between channel 1 of both devices
- A stream should appear at resolution of 800x600 and 30 fps

**Comment by dmalon** [comment]
As the PO I consider this story complete and closed

**Comment by felixlapierre** [comment]
Thanks Dan!
