### ISSUE TITLE
Acceptance test for #51 As a user, I want to log in to the admin console

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#289]
Steps:
- Run the frontend and backend
- Open the frontend
- You should be redirected to the login page
- Accessing any other page should redirect to the login page
- Enter the username "admin" and the password "admin" and click login
- You should be redirected to the dashboard
- The admin panel card should be visible

- Validate that all app functionality works as expected

> Device list page shows a list of all devices
> Stream list page shows a list of all streams
> Log list page shows a list of all logs
> Stream creation page allows the creation of streams between devices

- Click on the user icon on the top right of the screen
- You should be redirected to the login page
- Accessing any other page should redirect to the login page

- Use Postman to create a non-admin user in the system
- Enter the credentials of the non-admin user
- You should be redirected to the dashboard page
- The admin panel should not be visible
- All other app functionality should work as expected

**Comment by dmalon** [comment]
As PO I consider this story complete and closed

**Comment by felixlapierre** [comment]
Thanks Dan!
