### ISSUE TITLE
Acceptance test for #137 As a super user, I want to create a new account in the admin console

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#290]
Steps:
- Run the backend and frontend
- Open the frontend
- Enter the credentials of a superuser or admin account (such as username: admin, password: admin for the local development profile)
- Go to the dashboard
- Click on the create user button in the admin panel
- Enter a username and password for the new user and click on the create button
- You should be redirected to the dashboard
- Click on the user icon on the right of the header bar to log out
- Enter the credentials of the newly created user and click login
- You should be redirected to the dashboard
- The admin panel should not be visible, but all other app functionality should still work

**Comment by dmalon** [comment]
As the PO I consider this story complete and closed.

**Comment by felixlapierre** [comment]
Thanks Dan!
