### ISSUE TITLE
Acceptance test for #139 As a user, I want to view statistics about the performance of an ongoing stream

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#291]
Steps
- Start the frontend and backend
- Start the sample sender and receiver
- Register the sample sender and receiver in the system
- Open the frontend
- Go to the create streams page
- Create a stream between the two sample devices you are running
- Wait for the devices to start streaming
- Go to the stream details page for the newly created stream
- You should see the stream statistics for the stream displayed on the stream details page

The statistics displayed should be the ones in this image (minus SID)
![image.png](https://images.zenhubusercontent.com/5e15d6546da42b6dfe054be4/f6bdb911-dc3e-437f-963d-2d619e87374a)

**Comment by dmalon** [comment]
As PO I consider this story complete and closed

**Comment by felixlapierre** [comment]
Thanks Dan!
