### ISSUE TITLE
Undefined behavior when closing a stream

### ISSUE THREAD

**Issue by pobudzey** [bean-pod/switchboard#312]
Steps to reproduce:
* Start the frontend, backend, sample sender, and sample receiver
* Click the register button on both sample apps
* Open the admin panel
* Open the streams page
* Create a stream between both sample apps
* On the sample sender, select a file and click start
* Click start on the sample receiver
* Close the video manually either midway or after completion

Expected result:
* Either the video starts playing again, or the stream is deleted from the service and the video player closes

Actual result:
* Fatal error on the sender
![image](https://user-images.githubusercontent.com/43392224/107891015-19d93500-6eea-11eb-9bcc-3cde7092f2dc.png)
* Stream is still in the backend/service but nothing is happening in the sample apps

**Comment by felixlapierre** [comment]
PR: https://github.com/bean-pod/switchboard-samples/pull/13
