### ISSUE TITLE
Assign the superuser username, password and JWT Token secret in the CI/CD Pipeline

### ISSUE THREAD

**Issue by FGRCL** [bean-pod/switchboard#315]
The superuser username, password, and JWT Token should be set from a GitHub Secret for security reasons. The can be changed by with the following spring properties:
security.authentication.jwt.secret
security.authentication.superuser.username
security.authentication.superuser.password

**Comment by ButlerJAL** [comment]
Maybe there's a misunderstanding regarding the limitations of GitHub encrypted secrets. GitHub encrypted secrets are limited to GitHub Actions usage.

A full solution that deals with secure secret management is [HashiCorp Vault](https://www.hashicorp.com/products/vault), but requires setting up an infrastructure.

Storing secrets in configuration files is still widely done in practice. We just need to be careful to not publicly expose secrets being used in production, so, I would recommend keeping configuration files.

**Comment by ButlerJAL** [comment]
PR #412 deals with using System secrets stored on our Heroku continuous deployment instead of the publicly visible defaults we use for development and testing.
