### ISSUE TITLE
Add back test coverage "lost" in  DeviceDetails Refactor

### ISSUE THREAD

**Issue by jun-loke** [bean-pod/switchboard#369]
In the writing of #366  I refactored the DeviceList test which was covering many more components than anticipated. 
None of these components have their own test coverage. This needs to be recuperated.

Coverage on master before merge of #366 

![image](https://user-images.githubusercontent.com/35614138/110227251-6e0d7e80-7ec4-11eb-9823-302903ba73ce.png)

Coverage After merge: 93.5%
![image](https://user-images.githubusercontent.com/35614138/110227263-8bdae380-7ec4-11eb-893b-976c18e18e5b.png)

**Comment by felixlapierre** [comment]
Coverage is back up to 96.7% now, so we can close this

![image.png](https://images.zenhubusercontent.com/5e15d6546da42b6dfe054be4/acbe368d-ce13-4d88-a9d3-4e0875169033)
