### ISSUE TITLE
Acceptance test for #254 As a user, I want to rename devices in the system

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#388]
Steps:
- Run the frontend and backend
- Run one of the sample apps
- Register the device
- Open the frontend
- Go to the device list page
- Click on your device in the list to go to the detailed device information page
- Click on the pencil icon next to the device name
- Enter a new name for the device
- Click the save button

Expected:
- The new name is now the displayed name of the device

Next Steps:
- Return to the device list page

Expected:
- The device appears in the list with the new name that you assigned to it

**Comment by dmalon** [comment]
As PO I consider this story complete and closed.

**Comment by felixlapierre** [comment]
Thanks Dan!
