### ISSUE TITLE
Acceptance test for #140 As a user, I want to view logs of devices in the system

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#389]
Steps:
- Run the backend and the frontend
- Start the sample sender and receiver (referred to henceforth as device A and device B)
- Register the sample apps in the system
- Open the frontend and log in
- Go to the stream creation page
- Start a stream between both devices

The following logs should be visible
- Device A was registered
- Device A came online
- Device B was registered
- Device B came online
- A stream was started between output channel x of decoder A to input channel y of encoder B

Next steps:
- Go to the device list page
- Click on device A to go to the device details page of device A

The following logs should be visible
- Device A was registered
- Device A came online
- A stream was started between output channel x of decoder A to input channel y of encoder B

Repeat the previous steps and assertions for device B

**Comment by dmalon** [comment]
As PO I consider this story complete and closed

**Comment by felixlapierre** [comment]
Thanks Dan!
