### ISSUE TITLE
Sprint 9 System Testing

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#402]
Done
- #289 Log in to admin console 
- #388 Rename devices
- #137 Create new account
- #284 Restrict access to devices that i own
- #389 View logs of devices in the system
- #287 Log stream events

Ready to go

Waiting for feature to be complete

Will not system test
- #285 Multiple streams
- #288 Custom configuration
- #139 View statistics

**Comment by ButlerJAL** [comment]
Reopening this issue because last merge only partially completed this issue, and should not have closed it.
