### ISSUE TITLE
Repeated generation of online/offline logs when device is offline

### ISSUE THREAD

**Issue by felixlapierre** [bean-pod/switchboard#407]
Steps to reproduce:
- Start the backend and frontend
- Start a sample app and click register
- Click start on the sample app
- Close the sample app
- Wait 10 minutes
- Open the device list page
- Go to the view logs page

Expected result:
-The last log in the list indicates that the device went offline

Actual result:
- There is a log saying the device went offline, then immediately after there is a log saying the device went online

Every time you call the get all devices endpoint, or visit the view all devices page, two new logs are generated (one saying the device came online and one saying the device went offline)

**Comment by mohhef** [comment]
couldnt replicate, will talk to Felix tomorrow

**Comment by mohhef** [comment]
Could not replicate, verified with felix, cant reproduce.
