### ISSUE TITLE
Improve Breadcrumbs

### ISSUE THREAD

**Issue by gdzooks** [bean-pod/switchboard#451]
#430 has given us the need to pass a `StreamInfo` object into the breadcrumbs to navigate to the previous page (Stream Details, from Stream Statistics)

**Comment by jun-loke** [comment]
Original comment thread: https://github.com/bean-pod/switchboard/issues/430#issuecomment-813172884

**Comment by gdzooks** [comment]
opened so i can close with adding the objects to the breadcrumbs forreal :fire: \o/ :fire:
