### ISSUE TITLE
Post request to/encoder results in an internal server error

### ISSUE THREAD

**Issue by mohhef** [bean-pod/switchboard#61]
**OS:** Windows 10

**Steps to reproduce:** 

Make a post request to /encoder using the following body:
{
    "serialNumber": 2
}

**Expected result:**

The body should be populated in the database and the server should return a successful response.

**Actual result:**

Return of an internal server error.

**Visual proof:**

![image.png](https://images.zenhubusercontent.com/5e1e30bbe924e33c53b759d0/cf4ac784-a15b-4fb0-8ae7-a7dfbc8b25ed)

**Comment by FGRCL** [comment]
The payload for a post request should be something like this
```
{
  "displayName": "Camera 1B",
  "serialNumber": "BtmC8ckj"
}
```
But even then that should return you a **400** instead of a **500**

**Comment by mohhef** [comment]
@FGRCL with our current DB structure the device entity has all the details, the encoder/decoder has only a serial number that references to the device(displayName is an attribute of the device)
Its currently a 500 error because of an unexpected error that we are not throwing.

**Comment by mohhef** [comment]
Bug fixed in https://github.com/bean-pod/switchboard/commit/86b34ab3cf29fc77f6884af2b219cddb51efecbf
