### ISSUE TITLE
UI Prototypes

### ISSUE THREAD

**Issue by FGRCL** [bean-pod/switchboard#66]
Personas representing potential users and describe some of the tasks they will perform on the system.

Mockups linked to each user story for each sprint, all mockups will be annotated to explain the functionality of buttons/inputs/outputs, UI variations based on the personas, show updates to the UI mockups after receiving feedback from the product owner.

Artifact: Mockups, Persona descriptions

**Comment by felixlapierre** [comment]
See #99
