### ISSUE TITLE
Issue Tracker

### ISSUE THREAD

**Issue by FGRCL** [bean-pod/switchboard#68]
Create bug reports with replication steps, screenshots, links to the commits fixing the bug for traceability, links to commits updating tests to cover the reported bug. All issues related to bugs should be tagged with “bug” label, issues related to performance should be tagged with “performance” label.

Artifact: Bug reports

**Comment by felixlapierre** [comment]
Use label `bug` to represent issues that are bugs. Issues should contain full repro steps.
