### ISSUE TITLE
Refactoring Activity

### ISSUE THREAD

**Issue by FGRCL** [bean-pod/switchboard#69]
List the commits and pull requests in which refactoring took place. The commits and pull requests should explicitly mention/discuss/motivate the type(s) of refactoring. The complete list of refactoring types is available at https://refactoring.com/catalog/.

Artifact: Refactor list

**Comment by felixlapierre** [comment]
We should mark PRs that contain refactoring activity with the `refactoring` tab so it is easier to find them once we get to this
