### ISSUE TITLE
Code Quality and Security Report

### ISSUE THREAD

**Issue by FGRCL** [bean-pod/switchboard#71]
Software metrics [size, duplication, documentation, complexity, coupling, cohesion] evolution, Report the technical debt, security vulnerabilities, and code convention violations for the current release. List the commits and pull requests in which technical debt, security vulnerabilities, and code convention violations have been addressed. The commits and pull requests should explicitly mention/discuss/motivate the type(s) of technical debt addressed.

Artifact: Code quality report
> 99% sure he wants SonarQube for this

**Comment by felixlapierre** [comment]
Use the `code quality` labels to mark pull requests that address issues such as these
