### ISSUE TITLE
API specs should use Sender and Receiver instead of Encoder and Receiver

### ISSUE THREAD

**Issue by FGRCL** [bean-pod/switchboard#73]
**OS**
Windows 10

**Steps to reproduce**
Open the service/switchboardapp/contracts/api-spec.yaml file

**Expected result:**
The spec specifies encoder/decoder instead of sender/receiver

**Actual result:**
The spec specifies encoder/decoder

**Visual proof**
![image](https://user-images.githubusercontent.com/35940434/94973794-a0ace880-04da-11eb-9580-715c05ba68c7.png)

**Comment by mohhef** [comment]
@FGRCL Can you please explain what is the expected behavior? Did you mean that the endpoints is not currently following the spec?

**Comment by FGRCL** [comment]
This bug will not be fixed as we have decided to stick with encoder/decoder.
