### ISSUE TITLE
API Schemas shoud be postfixed with "Model"

### ISSUE THREAD

**Issue by FGRCL** [bean-pod/switchboard#74]
**Steps to reproduce**
1. open the file at service/switchboardapp/contracts/api-spec.yaml

**Screenshot**
![image](https://user-images.githubusercontent.com/35940434/94973937-09946080-04db-11eb-9c85-db9ea53d35f4.png)

**Comment by mohhef** [comment]
This bug was fixed in this pull request: https://github.com/bean-pod/switchboard/pull/86
